### ISSUE TITLE
Any demos ?

### ISSUE THREAD

**Issue by shtefcs** [JakeLin/cocos2d-meteor#1]
Hi there,

Is there any demo ?

**Comment by JakeLin** [comment]
Hi, 

You can follow the read me file to create a live demo like http://cocos2d.meteor.com/

Thanks
Jake

**Comment by shtefcs** [comment]
Tnx Jake, I just checked fast description and didn't see the link.

I checked demo, should something happen there http://screencast.com/t/KqtcZsXHRu ?

**Comment by JakeLin** [comment]
Hi Stefan,

It is a very simple game to demo how to use cocos2d-meteor. If you are
interested in coco2d-js, please check out their demo.

http://cocos2d-x.org/js-tests/
http://www.cocos2d-x.org/MoonWarriors/index.html
http://www.cocos2d-x.org/js-tests/

Thanks
Jake

**Comment by shtefcs** [comment]
Thats what i am talking about :D. Tnx man. You should definitely put this demos into Repo description so more people can see it.
