### ISSUE TITLE
Newer version of Cocos2D-JS?

### ISSUE THREAD

**Issue by shibekin69** [JakeLin/cocos2d-meteor#2]
Hi JakeLin,

Just wondering if there will be updates made to Cocos2D-JS in this package?

**Comment by JakeLin** [comment]
I am focus on iOS dev now, see whether I will have some spare time.

**Comment by andrewash** [comment]
@shibekin69 I've created a pull request with an update to Cocos2d-js version 3.9, the latest version

**Comment by shibekin69** [comment]
@JakeLin  @andrewash Oh all right, thanks for that!

**Comment by JakeLin** [comment]
@andrewash thanks
